# 使用 Python 3.8 版本的基礎映像
FROM python:3.8-slim-buster

# 設定工作目錄為 /app
WORKDIR /app

# 將當前目錄的內容複製到 /app 中
ADD . /app

# 安裝 Flask 和其它依賴
RUN pip install flask openai azure-cognitiveservices-speech

# 指定映像的運行時監聽的埠號
EXPOSE 5000

# 運行 Flask 應用
CMD ["python", "your_flask_app.py"]

#docker build -t your_flask_app:latest .

#docker run -p 5000:5000 your_flask_app:latest
